### PR TITLE
Fix for inability to run Build.PL

### PR DESCRIPTION
**Pull request by spacebat**
I'm participating in the [2015 CPAN PR Challenge](http://blogs.perl.org/users/neilb/2014/12/take-the-2015-cpan-pull-request-challenge.html) and was assigned this dist for February.

Turns out I couldn't install the module by hand, because Build.PL failed due to my lack of several build dependencies. I have modified My::Builder so that the modules I was missing are not loaded until Build.PL run time, which allows the M::B system to complete the process of creating the Build script. This allowed me to install the module and run the tests, which passed.

I've also deleted a few bits of stray whitespace, added a .gitignore and a .dir-locals.el which helps ensure emacs/cperl users use your indentation preferences.

I hope this PR is useful. Let me know if there's anything in particular that needs some attention.

### CODE REVIEW

**Comment by plicease** [comment]
`Archive::Extract` and `File::Copy::Recursive` are in the configure_requires, which means that they will be downloaded and installed by the cpan client before running `perl Build.PL`.

**Comment by spacebat** [comment]
Hi, you're quite right, sorry for the spam. `cpanm --installdeps .` is what I should have done. If you like I'll submit a new PR with the My::Builder modifications removed.

I'd like to help out any way I can, just let me know.

**Comment by plicease** [comment]
This isn't spam :)  Also I am not the maintainer of this distro, although I do have a commit bit, so I was more commenting on that one aspect.  I think the other stuff is good, although I can't comment on the .el stuff I am not an emacs user.

One thing that would be useful for this module is to check and see if newer binaries of CMake are available for any platform(s) that you have access to.  I did this a while ago for Linux and MSWin32:

https://github.com/PerlGameDev/Alien-CMake/commit/e6c72269e0e9a47dde3e474d090da7acf066d0bd

There may be newer versions available for Linux and Windows now, and I am pretty sure there are newer versions for other platforms that I were not a priority for me back then (OS X, freebsd, netbsd, solaris?)  Please do not update any platforms that you cannot actually verify though.

**Comment by plicease** [comment]
Another area that could help out is I notice there are a bunch of failures on Linux listed on cpantesters:

http://matrix.cpantesters.org/?dist=Alien-CMake+0.05

I just tried to reproduce this but installing worked for me.  If you can reproduce the problem and fix it that would be terrific.  I always hate to see so much red in the cpantesters matrix :)

**Pull request closed without merging**
